### ISSUE TITLE
ExecutionIdentity in Agent

### ISSUE THREAD

**Issue by KaNaPaPi** [relativitydev/relativity-templates#1]
In this file: relativity-templates-master\Exports\Agent\Project\Relativity Agent.cs

You have this line: using (IRSAPIClient rsapiClient = Helper.GetServicesManager().CreateProxy<IRSAPIClient>(ExecutionIdentity.CurrentUser))

There shouldn't be a CurrentUser in an Agent.  Shouldn't this be changed to ExecutionIdentity.System for an Agent?

**Comment by calimetikcura** [comment]
In Agents, ExecutionIdentity.CurrentUser and ExecutionIdentity.System refer to the same account.
